# Generated by Django 3.1.4 on 2021-01-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('venue', '0004_auto_20201209_0010'),
	]

	operations = [
		migrations.CreateModel(
			name='ItemCategory',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True, null=True)),
				('modified_at', models.DateTimeField(auto_now=True, null=True)),
				('name', models.CharField(max_length=220, unique=True)),
				('venue', models.ForeignKey(blank=True, null=True,
											on_delete=django.db.models.deletion.SET_NULL,
											related_name='categories', to='venue.venue')),
			],
			options={
				'unique_together': {('name', 'venue')},
			},
		),
		migrations.CreateModel(
			name='ItemSubCategory',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True, null=True)),
				('modified_at', models.DateTimeField(auto_now=True, null=True)),
				('name', models.CharField(max_length=220)),
				('category', models.ForeignKey(blank=True, null=True,
											   on_delete=django.db.models.deletion.SET_NULL,
											   related_name='subcategories',
											   to='inventory.itemcategory')),
			],
			options={
				'unique_together': {('category', 'name')},
			},
		),
		migrations.CreateModel(
			name='ItemVendor',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True, null=True)),
				('modified_at', models.DateTimeField(auto_now=True, null=True)),
				('name', models.CharField(max_length=220, unique=True)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='ItemType',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True, null=True)),
				('modified_at', models.DateTimeField(auto_now=True, null=True)),
				('name', models.CharField(max_length=220)),
				('description', models.TextField(blank=True, null=True)),
				('unit_buying_price',
				 models.DecimalField(decimal_places=3, default=0, max_digits=13)),
				('unit_selling_price',
				 models.DecimalField(decimal_places=3, default=0, max_digits=13)),
				('barcode', models.CharField(blank=True, max_length=50, null=True)),
				('total_qty', models.IntegerField(default=0)),
				('available_qty', models.IntegerField(default=0)),
				('latest_qty', models.IntegerField(default=0)),
				('image_url', models.CharField(blank=True, max_length=200, null=True)),
				('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
												  related_name='items',
												  to='inventory.itemsubcategory')),
				('vendor',
				 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
								   related_name='items', to='inventory.itemvendor')),
			],
			options={
				'unique_together': {('name', 'subcategory')},
			},
		),
	]
