# Generated by Django 3.1.4 on 2021-01-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together={('name', 'subcategory', 'vendor')},
        ),
    ]
