# Generated by Django 3.1.4 on 2021-01-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_auto_20201209_0010'),
        ('inventory', '0003_itemtype_venue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together={('name', 'subcategory', 'vendor', 'venue')},
        ),
    ]
