# Generated by Django 3.1.4 on 2021-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('inventory', '0006_auto_20211227_1740'),
	]

	operations = [
		migrations.AddField(
			model_name='itemtype',
			name='unit_buying_price_per_meter',
			field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13,
									  null=True),
		),
		migrations.AddField(
			model_name='itemtype',
			name='unit_selling_price_per_meter',
			field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13,
									  null=True),
		),
	]
