# Generated by Django 3.1.4 on 2021-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('inventory', '0007_auto_20211227_1748'),
	]

	operations = [
		migrations.AddField(
			model_name='itemtype',
			name='ref',
			field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
		),
	]
