# Generated by Django 3.1.4 on 2021-12-28 12:47

from django.db import migrations


def fill_Refs(apps, schema_editor, reverse=False):
	ItemType = apps.get_model('inventory', 'ItemType')

	if reverse:
		for item in ItemType.objects.iterator():
			item.ref = None
			item.save()
		return

	for item in ItemType.objects.iterator():
		item.ref = "{}{}{}".format("ITM", item.created_at.month, format(item.pk, '06d'))
		item.save()


def revert_fill_refs(apps, schema_editor):
	fill_Refs(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):
	dependencies = [
		('inventory', '0008_itemtype_ref'),
	]
	operations = [
		migrations.RunPython(fill_Refs, revert_fill_refs)
	]
