# Generated by Django 3.1.4 on 2020-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Permission',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True, null=True)),
				('modified_date', models.DateTimeField(auto_now=True, null=True)),
				('permission_name', models.CharField(max_length=100, unique=True)),
			],
			options={
				'abstract': False,
			},
		),
	]
