# Generated by Django 3.1.4 on 2020-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('permission', '0002_auto_20201208_1822'),
	]

	operations = [
		migrations.AlterField(
			model_name='permission',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
	]
