version: "3.1"

services:
  sales-api:
    build: .
    image: sales-api
    container_name: sales-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    network_mode: host
    environment:
      - ENV=prod
      - DATABASE_URL=postgres://postgres@localhost:5432/sales_db_prod
      - BASE_URL=http://localhost:8000/
      - EMAIL_HOST_USER=ronireiosantos@gmail.com
      - EMAIL_HOST_PASSWORD=kiyvuylobsrbyknp
    command: bash -c "pip install -r requirements.txt && bash ./docker/run.sh"
