# Generated by Django 3.1.4 on 2020-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('permission', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='DashboardSection',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True, null=True)),
				('modified_date', models.DateTimeField(auto_now=True, null=True)),
				('route_name', models.CharField(max_length=100)),
				('name', models.CharField(max_length=100, unique=True)),
				('is_visible_to_all', models.BooleanField(default=False)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='VenueViewerType',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True, null=True)),
				('modified_date', models.DateTimeField(auto_now=True, null=True)),
				('name', models.CharField(max_length=100)),
				('permissions', models.ManyToManyField(to='permission.Permission')),
				('sections',
				 models.ManyToManyField(related_name='viewer_types', to='user.DashboardSection')),
			],
		),
	]
