# Generated by Django 3.1.4 on 2020-12-04 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('user', '0001_initial'),
		('venue', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name='venueviewertype',
			name='users',
			field=models.ManyToManyField(related_name='viewer_types', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='venueviewertype',
			name='venue',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
		),
		migrations.AlterUniqueTogether(
			name='venueviewertype',
			unique_together={('venue', 'name')},
		),
	]
