# Generated by Django 3.1.4 on 2020-12-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
        ('user', '0002_auto_20201204_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueviewertype',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.role'),
        ),
    ]
