# Generated by Django 3.1.4 on 2020-12-08 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
	dependencies = [
		('venue', '0002_auto_20201208_1822'),
		('user', '0003_auto_20201207_1214'),
	]

	operations = [
		migrations.RenameField(
			model_name='dashboardsection',
			old_name='created_date',
			new_name='modified_at',
		),
		migrations.RenameField(
			model_name='venueviewertype',
			old_name='created_date',
			new_name='modified_at',
		),
		migrations.RemoveField(
			model_name='dashboardsection',
			name='modified_date',
		),
		migrations.RemoveField(
			model_name='venueviewertype',
			name='modified_date',
		),
		migrations.AddField(
			model_name='dashboardsection',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='venueviewertype',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='venueviewertype',
			name='venue',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
									related_name='viewer_types', to='venue.venue'),
		),
	]
