# Generated by Django 3.1.4 on 2020-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('user', '0005_auto_20201208_2254'),
	]

	operations = [
		migrations.AlterField(
			model_name='dashboardsection',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='venueviewertype',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
	]
