# Generated by Django 3.1.4 on 2021-11-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201209_0010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueviewertype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='venueviewertype',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='venueviewertype',
            name='role',
        ),
        migrations.RemoveField(
            model_name='venueviewertype',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='venueviewertype',
            name='users',
        ),
        migrations.RemoveField(
            model_name='venueviewertype',
            name='venue',
        ),
        migrations.DeleteModel(
            name='DashboardSection',
        ),
        migrations.DeleteModel(
            name='VenueViewerType',
        ),
    ]
