# Generated by Django 3.1.4 on 2020-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('venue', '0003_auto_20201208_2106'),
	]

	operations = [
		migrations.AlterField(
			model_name='role',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='user',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='userdata',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='usersvenues',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='usertype',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='venue',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='venuesetting',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
		migrations.AlterField(
			model_name='venuesettingvalue',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
	]
