# Generated by Django 3.1.4 on 2020-12-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Language',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True, null=True)),
				('modified_date', models.DateTimeField(auto_now=True, null=True)),
				('code', models.CharField(max_length=10, unique=True)),
				('name', models.CharField(max_length=100, unique=True)),
				('active', models.BooleanField(default=True)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='Term',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True, null=True)),
				('modified_date', models.DateTimeField(auto_now=True, null=True)),
				('key',
				 models.CharField(help_text='The key used in the front-end, e.g. `INDEX_title`',
								  max_length=150)),
				('description',
				 models.TextField(blank=True, help_text='Optional explanation of the key')),
			],
			options={
				'ordering': ('key',),
			},
		),
		migrations.CreateModel(
			name='Translation',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True, null=True)),
				('modified_date', models.DateTimeField(auto_now=True, null=True)),
				('value', models.TextField()),
				('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
											   to='terminology.language')),
				('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
										   to='terminology.term')),
			],
			options={
				'ordering': ('term__key', 'language__code'),
			},
		),
	]
