# Generated by Django 3.1.4 on 2020-12-08 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
	dependencies = [
		('venue', '0002_auto_20201208_1822'),
		('terminology', '0002_auto_20201204_1910'),
	]

	operations = [
		migrations.RenameField(
			model_name='language',
			old_name='created_date',
			new_name='modified_at',
		),
		migrations.RenameField(
			model_name='term',
			old_name='created_date',
			new_name='modified_at',
		),
		migrations.RenameField(
			model_name='translation',
			old_name='created_date',
			new_name='modified_at',
		),
		migrations.RemoveField(
			model_name='language',
			name='modified_date',
		),
		migrations.RemoveField(
			model_name='term',
			name='modified_date',
		),
		migrations.RemoveField(
			model_name='translation',
			name='modified_date',
		),
		migrations.AddField(
			model_name='language',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='term',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='translation',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='translation',
			name='language',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
									related_name='translations', to='terminology.language'),
		),
		migrations.AlterField(
			model_name='translation',
			name='term',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
									related_name='translations', to='terminology.term'),
		),
		migrations.AlterField(
			model_name='translation',
			name='venue',
			field=models.ForeignKey(blank=True, null=True,
									on_delete=django.db.models.deletion.SET_NULL,
									related_name='translations', to='venue.venue'),
		),
	]
