# Generated by Django 3.1.4 on 2020-12-08 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('venue', '0003_auto_20201208_2106'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='AuditLog',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('modified_at', models.DateTimeField(auto_now=True, null=True)),
				('table_name', models.CharField(max_length=100)),
				('table_pk', models.CharField(max_length=100)),
				('action', models.CharField(max_length=100)),
				('description', models.TextField(blank=True, null=True)),
				('prev_entity', models.JSONField(blank=True, null=True)),
				('new_entity', models.JSONField(blank=True, null=True)),
				('user', models.ForeignKey(blank=True, null=True,
										   on_delete=django.db.models.deletion.SET_NULL,
										   related_name='auditlogs', to=settings.AUTH_USER_MODEL)),
				('venue', models.ForeignKey(blank=True, null=True,
											on_delete=django.db.models.deletion.SET_NULL,
											related_name='auditlogs', to='venue.venue')),
			],
			options={
				'abstract': False,
			},
		),
	]
