# Generated by Django 3.1.4 on 2020-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('auditlogs', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='auditlog',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
	]
