# Generated by Django 3.1.4 on 2021-01-03 10:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0002_auto_20201209_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_entity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='prev_entity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
