# Generated by Django 3.1.4 on 2021-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0003_auto_20210103_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_entity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='prev_entity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
