# Generated by Django 3.1.4 on 2021-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('auditlogs', '0004_auto_20210103_1038'),
	]

	operations = [
		migrations.AlterField(
			model_name='auditlog',
			name='table_pk',
			field=models.CharField(blank=True, max_length=100, null=True),
		),
	]
