# Generated by Django 3.1.4 on 2021-01-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('auditlogs', '0005_auto_20210103_1114'),
	]

	operations = [
		migrations.AlterField(
			model_name='auditlog',
			name='table_pk',
			field=models.CharField(default=1, max_length=100),
			preserve_default=False,
		),
	]
