# Generated by Django 3.1.4 on 2021-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('sales', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='itemsale',
			name='deleted',
			field=models.BooleanField(null=True),
		),
		migrations.AddField(
			model_name='itemsale',
			name='deletion_reason',
			field=models.TextField(null=True),
		),
	]
