# Generated by Django 3.1.4 on 2021-11-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20211110_1506'),
        ('sales', '0002_auto_20210103_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsale',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemsale',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_sold', to=settings.AUTH_USER_MODEL),
        ),
    ]
