# Generated by Django 3.1.4 on 2021-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('sales', '0003_auto_20211110_1506'),
	]

	operations = [
		migrations.AddField(
			model_name='itemsale',
			name='sold_length',
			field=models.DecimalField(blank=True, decimal_places=3,
									  help_text='Length of wire sold in metres', max_digits=13,
									  null=True),
		),
	]
