# Generated by Django 3.1.4 on 2021-12-28 12:47

from django.db import migrations


def fill_Refs(apps, schema_editor, reverse=False):
	ItemSale = apps.get_model('sales', 'ItemSale')

	if reverse:
		for sale in ItemSale.objects.iterator():
			sale.ref = None
			sale.save()
		return

	for sale in ItemSale.objects.iterator():
		sale.ref = "{}{}{}".format("SAL", sale.created_at.month, format(sale.pk, '06d'))
		sale.save()


def revert_fill_refs(apps, schema_editor):
	fill_Refs(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):
	dependencies = [
		('sales', '0006_itemsale_ref'),
	]
	operations = [
		migrations.RunPython(fill_Refs, revert_fill_refs)
	]
