# Generated by Django 3.1.4 on 2021-11-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_auto_20211110_1506'),
        ('customers', '0002_customer_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.venue'),
        ),
    ]
