# Generated by Django 3.1.4 on 2021-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('customers', '0003_auto_20211110_1506'),
	]

	operations = [
		migrations.AddField(
			model_name='customer',
			name='ref',
			field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
		),
	]
