# Generated by Django 3.1.4 on 2021-12-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('customers', '0005_backfill_customer_ref'),
	]

	operations = [
		migrations.AlterField(
			model_name='customer',
			name='address',
			field=models.CharField(blank=True, max_length=200, null=True),
		),
		migrations.AlterField(
			model_name='customer',
			name='contact',
			field=models.CharField(blank=True, max_length=20, null=True),
		),
		migrations.AlterField(
			model_name='customer',
			name='email',
			field=models.EmailField(blank=True, max_length=254, null=True),
		),
	]
