# Generated by Django 3.1.4 on 2020-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Company',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
										verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True, null=True)),
				('modified_date', models.DateTimeField(auto_now=True, null=True)),
				('name', models.CharField(max_length=45)),
				('active', models.IntegerField(default=True)),
				('address1', models.CharField(blank=True, max_length=100, null=True)),
				('address2', models.CharField(blank=True, max_length=100, null=True)),
				('postcode', models.CharField(blank=True, max_length=45, null=True)),
				('city', models.CharField(blank=True, max_length=100, null=True)),
				('country', models.CharField(default='Uganda', max_length=100)),
				('deleted', models.BooleanField(default=False)),
			],
			options={
				'abstract': False,
			},
		),
	]
