# Generated by Django 3.1.4 on 2020-12-08 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
	dependencies = [
		('company', '0001_initial'),
	]

	operations = [
		migrations.RenameField(
			model_name='company',
			old_name='created_date',
			new_name='modified_at',
		),
		migrations.RemoveField(
			model_name='company',
			name='modified_date',
		),
		migrations.AddField(
			model_name='company',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
	]
